# Generated by Django 2.2.5 on 2022-11-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_Name', models.CharField(default='', max_length=255)),
                ('Minimum_Players', models.IntegerField(blank=True, default='')),
                ('Maximum_Players', models.IntegerField(blank=True, default='')),
                ('Game_Type', models.CharField(default='', max_length=255)),
                ('Estimated_Play_Time', models.CharField(default='', max_length=255)),
                ('Have_We_Played', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='', max_length=20)),
            ],
        ),
    ]
