# Generated by Django 2.2.5 on 2022-11-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardGameTracker', '0004_auto_20221103_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgames',
            name='Have_We_Played',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='', max_length=20),
        ),
    ]
