# Generated by Django 4.1.2 on 2022-10-18 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0002_alter_universityclasses_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universityclasses',
            options={'verbose_name_plural': 'University Classes'},
        ),
    ]
