# Generated by Django 4.1.2 on 2022-10-18 22:29

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universityclasses',
            options={'verbose_name': 'University Class', 'verbose_name_plural': 'University Classes'},
        ),
        migrations.AlterModelManagers(
            name='universityclasses',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
